# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-atmos-affected-stacks
  description: A composite workflow that runs the atmos describe affected command
  homepage: https://cloudposse.com/accelerate
  topics: ""
