name: "Atmos Affected Stacks"
description: "A GitHub Action to determine the affected stacks between two git refs"
author: hello@cloudposse.com
branding:
  icon: "file"
  color: "white"
inputs:
  head-ref:
    description: The head ref to checkout. If not provided, the head default branch is used.
    required: false
    default: ${{ github.sha }}
  default-branch:
    description: The default branch to use for the base ref.
    required: false
    default: ${{ github.event.repository.default_branch }}
  base-ref:
    description: The base ref to checkout. If not provided, the head default branch is used.
    required: false
  install-atmos:
    description: Whether to install atmos
    required: false
    default: "true"
  atmos-version:
    description: The version of atmos to install
    required: false
    default: ">= 1.63.0"
  atmos-config-path:
    description: The path to the atmos.yaml file
    required: true
  atmos-pro-upload:
    description: Whether to upload affected stacks directly to Atmos Pro
    required: false
    default: "false"
  atmos-pro-base-url:
    description: The base URL of Atmos Pro
    required: false
    default: "https://app.cloudposse.com"
  atmos-pro-token:
    description: The API token to allow Atmos Pro to upload affected stacks
    required: false
    default: ""
  atmos-include-spacelift-admin-stacks:
    description: Whether to include the Spacelift admin stacks of affected stacks in the output
    required: false
    default: "false"
  atmos-include-dependents:
    description: Whether to include dependents of affected stacks in the output
    required: false
    default: "false"
  install-jq:
    description: Whether to install jq
    required: false
    default: "false"
  jq-version:
    description: The version of jq to install if install-jq is true
    required: false
    default: "1.6"
  jq-force:
    description: Whether to force the installation of jq
    required: false
    default: "true"
  nested-matrices-count:
    required: false
    description: "Number of nested matrices that should be returned as the output (from 1 to 3)"
    default: "2"
outputs:
  affected:
    description: The affected stacks
    value: ${{ steps.affected.outputs.affected }}
  has-affected-stacks:
    description: Whether there are affected stacks
    value: ${{ steps.affected.outputs.affected != '[]' }}
  matrix:
    description: The affected stacks as matrix structure suitable for extending matrix size workaround (see README)
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.head-ref }}

    - if: ${{ inputs.install-jq == 'true' }}
      uses: dcarbone/install-jq-action@v2.1.0
      with:
        version: ${{ inputs.jq-version }}
        force: ${{ inputs.jq-force }}

    - if: ${{ inputs.install-atmos == 'true' }}
      uses: cloudposse/github-action-setup-atmos@v2
      with:
        atmos-version: ${{ inputs.atmos-version }}
        install-wrapper: false

    - name: Set vars
      shell: bash
      run: |-
        echo "ATMOS_CLI_CONFIG_PATH=$(realpath ${{ inputs.atmos-config-path }})" >> $GITHUB_ENV

    - name: config
      shell: bash
      id: config
      run: |-
        echo "opentofu-version=$(atmos describe config -f json | jq -r '.integrations.github.gitops["opentofu-version"]')" >> $GITHUB_OUTPUT        
        echo "terraform-version=$(atmos describe config -f json | jq -r '.integrations.github.gitops["terraform-version"]')" >> $GITHUB_OUTPUT      
        echo "group-by=$(atmos describe config -f json | jq -r '.integrations.github.gitops.matrix["group-by"]')" >> $GITHUB_OUTPUT
        echo "sort-by=$(atmos describe config -f json | jq -r '.integrations.github.gitops.matrix["sort-by"]')" >> $GITHUB_OUTPUT

    - name: Install Terraform
      if: ${{ steps.config.outputs.terraform-version != '' && steps.config.outputs.terraform-version != 'null' }}
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ steps.config.outputs.terraform-version }}
        terraform_wrapper: false

    - name: Install OpenTofu
      if: ${{ steps.config.outputs.opentofu-version != '' && steps.config.outputs.opentofu-version != 'null' }}
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: ${{ steps.config.outputs.opentofu-version }}
        tofu_wrapper: false

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # atmos describe affected requires the main branch of the git repo to be present on disk so it can compare the
    # current branch to it to determine the affected stacks. This is different from a file-based git diff in that we
    # look at the contents of the stack files to determine if any have changed.
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.default-branch }}
        path: base-ref
        fetch-depth: 0

    - name: checkout base ref
      id: base-ref
      shell: bash
      run: git checkout ${{ inputs.base-ref }}
      working-directory: base-ref

    - name: atmos affected stacks for atmos pro
      id: affected-pro
      if: ${{ inputs.atmos-pro-upload == 'true' }}
      env:
        ATMOS_PRO_BASE_URL: ${{ inputs.atmos-pro-base-url }}
        ATMOS_PRO_TOKEN: ${{ inputs.atmos-pro-token }}
      shell: bash
      run: |
        atmos describe affected --upload --verbose=true --repo-path "$GITHUB_WORKSPACE/base-ref"

    - name: atmos affected stacks
      id: affected
      if: ${{ inputs.atmos-pro-upload == 'false' }}
      shell: bash
      run: |
        if [[ "${{ inputs.atmos-include-spacelift-admin-stacks }}" == "true" ]]; then
          atmos describe affected --file affected-stacks.json --verbose=true --repo-path "$GITHUB_WORKSPACE/base-ref" --include-spacelift-admin-stacks=true
        elif [[ "${{ inputs.atmos-include-dependents }}" == "true" ]]; then
          atmos describe affected --file affected-stacks.json --verbose=true --repo-path "$GITHUB_WORKSPACE/base-ref" --include-dependents=true
        else
          atmos describe affected --file affected-stacks.json --verbose=true --repo-path "$GITHUB_WORKSPACE/base-ref"
        fi
        affected=$(jq -c '.' affected-stacks.json)
        printf "%s" "affected=$affected" >> $GITHUB_OUTPUT

    - name: No changes summary
      if: ${{ inputs.atmos-pro-upload == 'false' && steps.affected.outputs.affected == '[]' }}
      shell: bash
      run: |-
        cat ${{ github.action_path }}/assets/summary.md >> $GITHUB_STEP_SUMMARY

    - uses: cloudposse/github-action-matrix-extended@v0
      id: matrix
      if: ${{ inputs.atmos-pro-upload == 'false' }}
      with:
        matrix: affected-stacks.json
        sort-by: ${{ steps.config.outputs.sort-by }}
        group-by: ${{ steps.config.outputs.group-by }}
        nested-matrices-count: ${{ inputs.nested-matrices-count }}
