name: "Atmos Affected Stacks"
description: "A GitHub Action to determine the affected stacks between two git refs"
author: hello@cloudposse.com
branding:
  icon: "file"
  color: "white"
inputs:
  head-ref:
    description: The head ref to checkout. If not provided, the head default branch is used.
    required: false
    default: ${{ github.sha }}
  default-branch:
    description: The default branch to use for the base ref.
    required: false
    default: ${{ github.event.repository.default_branch }}
  base-ref:
    description: The base ref to checkout. If not provided, the head default branch is used.
    required: false
  install-atmos:
    description: Whether to install atmos
    required: false
    default: "true"
  atmos-gitops-config-path:
    description: The path to the atmos-gitops.yaml file
    required: false
    default: ./.github/config/atmos-gitops.yaml
  atmos-include-spacelift-admin-stacks:
    description: Whether to include the Spacelift admin stacks of affected stacks in the output
    required: false
    default: "false"
  install-terraform:
    description: Whether to install terraform
    required: false
    default: "true"
  install-jq:
    description: Whether to install jq
    required: false
    default: "false"
  jq-version:
    description: The version of jq to install if install-jq is true
    required: false
    default: "1.6"
  jq-force:
    description: Whether to force the installation of jq
    required: false
    default: "true"
  nested-matrices-count:
    required: false
    description: 'Number of nested matrices that should be returned as the output (from 1 to 3)'
    default: "2"
outputs:
  affected:
    description: The affected stacks
    value: ${{ steps.affected.outputs.affected }}
  has-affected-stacks:
    description: Whether there are affected stacks
    value: ${{ steps.matrix.outputs.matrix != '{"include":[]}' }}
  matrix:
    description: The affected stacks as matrix structure suitable for extending matrix size workaround (see README)
    value: ${{ steps.matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.head-ref }}

    - name: config
      uses: cloudposse/github-action-config-levels@nodejs20
      id: config
      with:
        output_properties: true
        patterns: |
          - ${{ inputs.atmos-gitops-config-path }}

    - if: ${{ inputs.install-terraform == 'true' }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ steps.config.outputs.terraform-version }}

    - if: ${{ inputs.install-atmos == 'true' }}
      uses: cloudposse/github-action-setup-atmos@v1.0.0
      with:
        atmos-version: ${{ steps.config.outputs.atmos-version }}
        install-wrapper: false

    - if: ${{ inputs.install-jq == 'true' }}
      uses: dcarbone/install-jq-action@v1.0.1
      with:
        version: ${{ inputs.jq-version }}
        force: ${{ inputs.jq-force }}

    # atmos describe affected requires the main branch of the git repo to be present on disk so it can compare the
    # current branch to it to determine the affected stacks. This is different from a file-based git diff in that we
    # look at the contents of the stack files to determine if any have changed.
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.default-branch }}
        path: main-branch
        fetch-depth: 0

    - name: checkout head ref
      id: base-ref
      shell: bash
      run: git checkout ${{ inputs.base-ref }}
      working-directory: main-branch

    - name: Set vars
      shell: bash
      run: |-
        echo "ATMOS_CLI_CONFIG_PATH=$(realpath ${{ steps.config.outputs.atmos-config-path }})" >> $GITHUB_ENV
        echo "ATMOS_BASE_PATH=${{ github.workspace }}" >> $GITHUB_ENV      

    - name: atmos affected stacks
      id: affected
      shell: bash
      run: |
        if [[ "${{ inputs.atmos-include-spacelift-admin-stacks }}" == "true" ]]; then
          atmos describe affected --file affected-stacks.json --verbose=true --repo-path "$GITHUB_WORKSPACE/main-branch" --include-spacelift-admin-stacks=true
        else
          atmos describe affected --file affected-stacks.json --verbose=true --repo-path "$GITHUB_WORKSPACE/main-branch"
        fi
        affected=$(jq -c '.' affected-stacks.json)
        printf "%s" "affected=$affected" >> $GITHUB_OUTPUT

    - uses: cloudposse/github-action-matrix-extended@v0
      id: matrix
      with:
        matrix: affected-stacks.json
        sort-by: ${{ steps.config.outputs.sort-by }}
        group-by: ${{ steps.config.outputs.group-by }}
        nested-matrices-count: ${{ inputs.nested-matrices-count }}
