name: Release
on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  github-action:
    uses: cloudposse/.github/.github/workflows/shared-release-branches.yml@4ae67ee1158b9c6466074b7729e1efe197cfd665 # main
    secrets: inherit
