name: Test atmos-affected-stacks positive
on:
  #  # Uncomment when test added first time to register workflow and comment it back after workflow would be registered
  #  #
  #  # Added pull_request to register workflow from the PR.
  #  # Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
  # pull_request: {}
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: add mock atmos to the path
        run: echo "./fixtures" >> $GITHUB_PATH

      - uses: ./
        id: current
        with:
          install-atmos: false
          atmos-config-path: "./components/terraform/test"
    outputs:
      affected: "${{ steps.current.outputs.affected }}"
      matrix: "${{ steps.current.outputs.matrix }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v1
        with:
          expected: '{"component":"datadog-integration","component_type":"terraform","component_path":"components/terraform/datadog-integration","stack":"core-gbl-dns","stack_slug":"core-gbl-dns-datadog-integration","spacelift_stack":"core-gbl-dns-datadog-integration","affected":"component"}'
          actual: "${{ needs.test.outputs.affected }}"
          comparison: contains
      - uses: nick-fields/assert-action@v1
        with:
          expected: '{"include":['
          actual: "${{ needs.test.outputs.matrix }}"
          comparison: contains
